# Generated by Django 4.2.4 on 2023-08-07 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Number',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_number', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session_Number',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Session_number', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('PORT', 'Portraits'), ('SEN', 'Senior Portraits'), ('FAM', 'Family Portraits'), ('WED', 'Weddings'), ('SPORT', 'Sports'), ('EVNT', 'Events'), ('DRONE', 'Drone Services'), ('HEAD', 'Headshots'), ('OTHER', 'Other')], max_length=100)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='Indianapolis', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='Indiana', max_length=100, null=True)),
                ('client_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client_number')),
                ('session_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.session_number')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_person', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('client_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client_number')),
            ],
        ),
    ]
