# Generated by Django 4.2.4 on 2023-08-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_client_number_client_number_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client_number',
            name='id',
        ),
        migrations.RemoveField(
            model_name='session_number',
            name='id',
        ),
        migrations.AddField(
            model_name='client_number',
            name='Client_Number',
            field=models.IntegerField(default='none', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='session_number',
            name='Session_Number',
            field=models.CharField(default='none', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client_number',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('PORT', 'Portraits'), ('SEN', 'Senior Portraits'), ('FAM', 'Family Portraits'), ('WED', 'Weddings'), ('SPORT', 'Sports'), ('EVNT', 'Events'), ('DRONE', 'Drone Services'), ('HEAD', 'Headshots'), ('OTHER', 'Other')], max_length=100, null=True),
        ),
    ]
