# Generated by Django 4.2.4 on 2023-08-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_number_id_remove_session_number_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_number',
            name='Client_Number',
            field=models.IntegerField(default=12345, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='session_number',
            name='Session_Number',
            field=models.CharField(default=12345, primary_key=True, serialize=False),
        ),
    ]
